name: presensigps
description: "Aplikasi Presensi Geolocation Mobile."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Networking ---
  # Koneksi API Laravel
  http: ^1.2.0

  # --- Storage ---
  # Token login session
  shared_preferences: ^2.2.2

  # --- Camera & Images ---
  # Foto selfie
  image_picker: ^1.0.7
  # Mengecilkan ukuran foto 
  flutter_image_compress: ^2.1.0

  # --- Location & Maps ---
  # Koordinat GPS
  geolocator: ^11.0.0
  # Menampilkan Peta
  flutter_map: ^6.1.0 
  # Koordinat flutter_map
  latlong2: ^0.9.0

  # --- Utilities ---
  # Tanggal dan waktu
  intl: ^0.19.0
  # izin aplikasi Kamera & Lokasi
  permission_handler: ^11.3.0

  # --- UI ---
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter standar Flutter
  flutter_lints: ^4.0.0

# Konfigurasi Aset
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/